#! /bin/sh

picom --experimental-backends &
pgrep -x sxhkd -m -1 > /dev/null || sxhkd -m -1 &
feh --bg-scale ~/Descargas/nier.jpg &
~/.config/polybar/launch.sh &
redshift -PO 3600 -b 0.6 &

bspc monitor -d I II III IV V VI VII #VIII IX X

bspc config border_width         1.8 
bspc config window_gap           9

#colors
bspc config normal_border_color "#eceff4"
bspc config focused_border_color "#5e81ac"
#bspc config presel_feedback_color "#30b7cb"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#lwd
bspc rule -a Zathura state=tiled
bspc rule -a mpv state=fullscreen
bspc rule -a Pavucontrol state=pseudo_tiled
bspc rule -a SimpleScreenRecorder state=pseudo_tiled
